### ISSUE TITLE
Application with Identifier was not found in the directory...

### ISSUE THREAD

**Issue by bforsyt4** [MarcelMeurer/PowerShellGallery-OneDrive#2]
After registering a new app in Azure Portal to support OD4B administration, I got an exception in the modal sign in window when executing PowerShell to create the access token:

Sorry, but we’re having trouble signing you in.
 
AADSTS700016: Application with identifier '832d6848-5460-4bb5-a04c-3809c94d6xxx' was not found in the directory '2edcd1f3-71c8-4ceb-a690-7e47de509xxx'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant...

I found that by editing the Azure registered app's manifest and set "availableToOtherTenants" from 'false' to 'true' I was able to generate an access token (but still needed to manually 'accept' in the modal sign in box).

**Comment by MarcelMeurer** [comment]
Hello @bforsyt4 : Is this issue solved with your configuration and can your app work after one authentication without problems (does you app uses refresh tokens to reauthenticate unattended?)?

**Comment by bforsyt4** [comment]
I didn’t get that far, and unfortunately haven’t been able to work on it lately.

Thanks!

Brian

**Comment by MarcelMeurer** [comment]
I close this issue. Please reopen it and contact me if you have further problems.
