### ISSUE TITLE
script trowing a unauthorized error

### ISSUE THREAD

**Issue by jvondermans** [MarcelMeurer/PowerShellGallery-OneDrive#4]
Hi Marcel,

Firtst of all; thanks for this module as Microsft doen't have any solution created for OneDrive.

I'm stuck with a Unauthorized error, but I can't figure out where it is stuck. I've followed the instructions for creating an app, that should be fine. When I run the line:

`$Auth=Get-ODAuthentication -ClientId "2831fc52-e1b8-4493-9f3a-a3dad74b2081" -AppKey "TqoSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="  -RedirectURI "http://sepago.de/1Drive4Business" -ResourceId "https://sepagogmbh-my.sharepoint.com/"`

I do get a token. that should mean the application itself works.

the permissions are set in a different way then your manual, but I do have the permissions:
![image](https://user-images.githubusercontent.com/32496711/60418982-94095880-9be4-11e9-8c90-28d9fe0da5d5.png)

This is more then required, but I added these just to make sure I have enough. could it be that there is a delay in authorizing? Or should I do something else? Or did I miss something?

**Comment by MarcelMeurer** [comment]
Hi.

This looks good. You have mor permision as needed.

If you use $auth - did you reference the right property?

Add-ODItem -AccessToken $auth.access_token -ResourceId $resourceIdGiven
-LocalFile "D:\Camtasia\Rec 05-19-19.trec" -ElementId 01BJ34VR6O3HUBOVAZOJDJPQ7HVO7SXCQX

Focus to "access_token".

An yes. It takes some times after you change the permission.

Did this works for you or do you have still problems?

**Comment by jvondermans** [comment]
Hi Marcel,

I don't see what I'm doing wrong, here the info I use:

token:
`token_type     : Bearer
scope          : AllSites.FullControl AllSites.Manage AllSites.Read AllSites.Write MyFiles.Read MyFiles.Write Sites.Search.All User.Read User.Read.All User.ReadWrite.All
expires_in     : 3600
ext_expires_in : 3600
expires_on     : 1562138903
not_before     : 1562135003
resource       : https://company-my.sharepoint.com/
access_token   : eyJ0eXAi-------u4lgvA
refresh_token  : AQA-------IroIAA
id_token       : eyJ0------MS4wIn0.
`

command:
`Get-ODChildItems -AccessToken $Auth.access_token -ResourceId "https://company-my.sharepoint.com/personal/adm-jv_company_nl/documents" -path "/"`

Error:
`Get-ODWebContent : Cannot access the api. Webrequest return code is: Unauthorized
Unauthorized
At C:\Program Files\WindowsPowerShell\Modules\OneDrive\2.2\OneDrive.psm1:474 char:18
+ ... ponseObject=Get-ODWebContent -AccessToken $AccessToken -ResourceId $R ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-ODWebContent`

**Comment by MarcelMeurer** [comment]
Could you try:
Get-ODChildItems -AccessToken $Auth.access_token -ResourceId "https://company-my.sharepoint.com/" -path "/"

Where ResourceId="https://company-my.sharepoint.com/" for Get-ODChildItems and for Get-ODAuthentication

**Comment by jvondermans** [comment]
Hi Marcel,

This works!! Does this mean that if I want to access another Onedrive I have to change the URL's in both Get-ODChildItems and for Get-ODAuthentication?

Thanks for all your help!

Update: it works now with al onedrives, looks like a a little hickup.

**Comment by MarcelMeurer** [comment]
Hi.

Yes - if the other OneDrive for Business in another tenant/organisation. 

No - if you want to access a shared OneDrive for Business in the same tenant/organisation (maybe from a colleague).
