### ISSUE TITLE
help needed with new Azure permissions management

### ISSUE THREAD

**Issue by audioscavenger** [MarcelMeurer/PowerShellGallery-OneDrive#8]
thanks for providing a guide to setup application, token, and other permissions needed to download from oneDrive business

However the screens have changed quite a lot. 365 is not an option anymore, it's called **Graph**.
Also, I enabled everything i could for ReadWrite under **Files** and **Sites** but no luck: i cannot upload files with _Add-ODItem_ . This is the error i have:

```
Add-ODItem : Upload error: Forbidden
Forbidden
+ ... $ReturnCode=Add-ODItem -AccessToken $Auth.access_token -ResourceId $R ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-ODItem
```

any idea? thanks

**Comment by MarcelMeurer** [comment]
Hi audioscavenger. Thanks. I updated the documentation. Please check if you have set the "Id tokens" checkbox while you configure the Azure application. Please reopen the issue if the problem still exist (we can have a skype session to figure out the problem).
